## ARTIFICIAL NEURAL NETWORKS

In [ ]:
# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

## Data Exploration and Preprocessing

### 1. Load and Explore the Dataset:

In [ ]:
# Load the dataset

In [2]:
df = pd.read_csv(r'C:\Users\sanket\Desktop\DS ASSIGNMENT\New folder\Neural networks\Neural networks\Alphabets_data.csv')
df

letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  \
0          T     2     8      3       5      1     8    13      0      6   
1          I     5    12      3       7      2    10     5      5      4   
2          D     4    11      6       8      6    10     6      2      6   
3          N     7    11      6       6      3     5     9      4      6   
4          G     2     1      3       1      1     8     6      6      6   
...      ...   ...   ...    ...     ...    ...   ...   ...    ...    ...   
19995      D     2     2      3       3      2     7     7      7      6   
19996      C     7    10      8       8      4     4     8      6      9   
19997      T     6     9      6       7      5     6    11      3      7   
19998      S     2     3      4       2      1     8     7      2      6   
19999      A     4     9      6       6      2     9     5      3      1   

       xybar  x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0          6      10       8      0       8      0       8  
1         13       3       9      2       8      4      10  
2         10       3       7      3       7      3       9  
3          4       4      10      6      10      2       8  
4          6       5       9      1       7      5      10  
...      ...     ...     ...    ...     ...    ...     ...  
19995      6       6       4      2       8      3       7  
19996     12       9      13      2       9      3       7  
19997     11       9       5      2      12      2       4  
19998     10       6       8      1       9      5       8  
19999      8       1       8      2       7      2       8  

[20000 rows x 17 columns]

In [3]:
df.head()

letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  xybar  \
0      T     2     8      3       5      1     8    13      0      6      6   
1      I     5    12      3       7      2    10     5      5      4     13   
2      D     4    11      6       8      6    10     6      2      6     10   
3      N     7    11      6       6      3     5     9      4      6      4   
4      G     2     1      3       1      1     8     6      6      6      6   

   x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0      10       8      0       8      0       8  
1       3       9      2       8      4      10  
2       3       7      3       7      3       9  
3       4      10      6      10      2       8  
4       5       9      1       7      5      10

In [4]:
df.describe()

xbox          ybox         width       height         onpix  \
count  20000.000000  20000.000000  20000.000000  20000.00000  20000.000000   
mean       4.023550      7.035500      5.121850      5.37245      3.505850   
std        1.913212      3.304555      2.014573      2.26139      2.190458   
min        0.000000      0.000000      0.000000      0.00000      0.000000   
25%        3.000000      5.000000      4.000000      4.00000      2.000000   
50%        4.000000      7.000000      5.000000      6.00000      3.000000   
75%        5.000000      9.000000      6.000000      7.00000      5.000000   
max       15.000000     15.000000     15.000000     15.00000     15.000000   

               xbar          ybar         x2bar         y2bar         xybar  \
count  20000.000000  20000.000000  20000.000000  20000.000000  20000.000000   
mean       6.897600      7.500450      4.628600      5.178650      8.282050   
std        2.026035      2.325354      2.699968      2.380823      2.488475   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        6.000000      6.000000      3.000000      4.000000      7.000000   
50%        7.000000      7.000000      4.000000      5.000000      8.000000   
75%        8.000000      9.000000      6.000000      7.000000     10.000000   
max       15.000000     15.000000     15.000000     15.000000     15.000000   

            x2ybar        xy2bar         xedge        xedgey         yedge  \
count  20000.00000  20000.000000  20000.000000  20000.000000  20000.000000   
mean       6.45400      7.929000      3.046100      8.338850      3.691750   
std        2.63107      2.080619      2.332541      1.546722      2.567073   
min        0.00000      0.000000      0.000000      0.000000      0.000000   
25%        5.00000      7.000000      1.000000      8.000000      2.000000   
50%        6.00000      8.000000      3.000000      8.000000      3.000000   
75%        8.00000      9.000000      4.000000      9.000000      5.000000   
max       15.00000     15.000000     15.000000     15.000000     15.000000   

            yedgex  
count  20000.00000  
mean       7.80120  
std        1.61747  
min        0.00000  
25%        7.00000  
50%        8.00000  
75%        9.00000  
max       15.00000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   letter  20000 non-null  object
 1   xbox    20000 non-null  int64 
 2   ybox    20000 non-null  int64 
 3   width   20000 non-null  int64 
 4   height  20000 non-null  int64 
 5   onpix   20000 non-null  int64 
 6   xbar    20000 non-null  int64 
 7   ybar    20000 non-null  int64 
 8   x2bar   20000 non-null  int64 
 9   y2bar   20000 non-null  int64 
 10  xybar   20000 non-null  int64 
 11  x2ybar  20000 non-null  int64 
 12  xy2bar  20000 non-null  int64 
 13  xedge   20000 non-null  int64 
 14  xedgey  20000 non-null  int64 
 15  yedge   20000 non-null  int64 
 16  yedgex  20000 non-null  int64 
dtypes: int64(16), object(1)
memory usage: 2.6+ MB


In [6]:
# Check for the number of classes
print("Number of classes:", df['letter'].nunique())
print("Class distribution:\n", df['letter'].value_counts())

Number of classes: 26
Class distribution:
 U    813
D    805
P    803
T    796
M    792
A    789
X    787
Y    786
N    783
Q    783
F    775
G    773
E    768
B    766
V    764
L    761
R    758
I    755
O    753
W    752
S    748
J    747
K    739
C    736
H    734
Z    734
Name: letter, dtype: int64


### 2. Data Preprocessing:

In [7]:
# Check for missing values
df.isnull().sum()

letter    0
xbox      0
ybox      0
width     0
height    0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: int64

In [9]:
# Separate features and target columns
y = df['letter']

In [10]:
y

0        T
1        I
2        D
3        N
4        G
        ..
19995    D
19996    C
19997    T
19998    S
19999    A
Name: letter, Length: 20000, dtype: object

In [11]:
x= df.drop(columns=['letter'])

In [12]:
x

xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  xybar  \
0         2     8      3       5      1     8    13      0      6      6   
1         5    12      3       7      2    10     5      5      4     13   
2         4    11      6       8      6    10     6      2      6     10   
3         7    11      6       6      3     5     9      4      6      4   
4         2     1      3       1      1     8     6      6      6      6   
...     ...   ...    ...     ...    ...   ...   ...    ...    ...    ...   
19995     2     2      3       3      2     7     7      7      6      6   
19996     7    10      8       8      4     4     8      6      9     12   
19997     6     9      6       7      5     6    11      3      7     11   
19998     2     3      4       2      1     8     7      2      6     10   
19999     4     9      6       6      2     9     5      3      1      8   

       x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0          10       8      0       8      0       8  
1           3       9      2       8      4      10  
2           3       7      3       7      3       9  
3           4      10      6      10      2       8  
4           5       9      1       7      5      10  
...       ...     ...    ...     ...    ...     ...  
19995       6       4      2       8      3       7  
19996       9      13      2       9      3       7  
19997       9       5      2      12      2       4  
19998       6       8      1       9      5       8  
19999       1       8      2       7      2       8  

[20000 rows x 16 columns]

In [ ]:
# Normalize the feature data

In [13]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()
x_normalized = scaler.fit_transform(x)
x_normalized

array([[-1.0576983 ,  0.29187713, -1.05327668, ..., -0.21908163,
        -1.4381527 ,  0.12291107],
       [ 0.51038497,  1.5023577 , -1.05327668, ..., -0.21908163,
         0.12008142,  1.35944092],
       [-0.01230945,  1.19973756,  0.43590966, ..., -0.8656262 ,
        -0.26947711,  0.74117599],
       ...,
       [ 1.03307939,  0.59449727,  0.43590966, ...,  2.36709667,
        -0.65903564, -2.35014863],
       [-1.0576983 , -1.22122359, -0.55688123, ...,  0.42746295,
         0.50963994,  0.12291107],
       [-0.01230945,  0.59449727,  0.43590966, ..., -0.8656262 ,
        -0.65903564,  0.12291107]])

In [ ]:
#Encoding the Target Variable: 

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
y_encoded

array([19,  8,  3, ..., 19, 18,  0])

In [ ]:
# split the data into traing and testing part

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x_normalized, y_encoded, test_size=0.2, random_state=42)

In [22]:
x_train

array([[-0.01230945, -0.01074302, -0.06048579, ..., -0.21908163,
         0.12008142,  0.12291107],
       [-0.01230945, -0.01074302,  0.43590966, ..., -0.21908163,
         0.12008142, -0.49535386],
       [-0.53500387, -0.6159833 , -0.55688123, ...,  0.42746295,
        -0.65903564, -1.11361878],
       ...,
       [-0.53500387, -0.91860345,  0.43590966, ..., -0.8656262 ,
        -0.26947711,  0.74117599],
       [-0.53500387,  0.29187713, -0.55688123, ..., -0.21908163,
        -1.04859417, -0.49535386],
       [-1.58039272, -1.22122359, -1.54967212, ..., -0.8656262 ,
        -1.4381527 , -0.49535386]])

In [23]:
x_test

array([[-0.53500387, -0.31336316, -0.06048579, ..., -0.8656262 ,
         1.288757  , -1.11361878],
       [-0.01230945,  1.19973756,  0.43590966, ...,  1.7205521 ,
         1.288757  , -1.73188371],
       [-0.53500387, -0.91860345, -0.06048579, ..., -1.51217078,
        -0.65903564,  0.12291107],
       ...,
       [ 0.51038497,  0.89711742,  0.93230511, ..., -0.21908163,
         0.12008142,  0.12291107],
       [-0.01230945, -0.6159833 , -0.06048579, ...,  1.07400752,
         2.06787406, -1.73188371],
       [-1.0576983 , -0.6159833 , -0.55688123, ...,  1.7205521 ,
        -0.65903564,  0.12291107]])

In [24]:
y_train

array([ 4,  4, 13, ..., 23,  8,  9])

In [25]:
y_test

array([19, 11,  0, ..., 16, 24, 24])

##  Model Implementation

In [26]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [27]:
# Define a basic ANN model
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(x_train.shape[1],)))  # Input layer
model.add(Dense(32, activation='relu'))  # Hidden layer
model.add(Dense(len(np.unique(y_encoded)), activation='softmax'))  # Output layer for classification

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [28]:
# Train the model
history = model.fit(x_train, y_train, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.2987 - loss: 2.5821 - val_accuracy: 0.6687 - val_loss: 1.1827
Epoch 2/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7009 - loss: 1.0453 - val_accuracy: 0.7491 - val_loss: 0.8919
Epoch 3/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7729 - loss: 0.7976 - val_accuracy: 0.7862 - val_loss: 0.7533
Epoch 4/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8093 - loss: 0.6582 - val_accuracy: 0.8062 - val_loss: 0.6679
Epoch 5/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8295 - loss: 0.5926 - val_accuracy: 0.8313 - val_loss: 0.5849
Epoch 6/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8461 - loss: 0.5362 - val_accuracy: 0.8403 - val_loss: 0.5342
Epoch 7/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8626 - loss: 0.4751 - val_accuracy: 0.8534 - val_loss: 0.4934
Epoch 8/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8698 - loss: 0.4339 - val_accuracy: 0.

In [30]:
# Make predictions on the test set
y_pred = model.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_pred_classes

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step


array([25, 11,  0, ..., 16, 24, 24], dtype=int64)

## Hyperparameter Tuning

In [31]:
import keras_tuner as kt

In [33]:
# Define a model-building function for Keras Tuner
def build_model(hp):
    model = Sequential()
    model.add(Dense(hp.Int('units_input', min_value=32, max_value=128, step=32), activation='relu', input_shape=(x_train.shape[1],)))
    for i in range(hp.Int('num_layers', 1, 3)):  # Vary number of layers
        model.add(Dense(hp.Int(f'units_{i}', min_value=32, max_value=128, step=32), activation='relu'))
    model.add(Dense(len(np.unique(y_encoded)), activation='softmax'))
    
    model.compile(optimizer=hp.Choice('optimizer', ['adam', 'sgd']),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

In [34]:
# Use Keras Tuner for hyperparameter tuning
tuner = kt.RandomSearch(build_model, objective='val_accuracy', max_trials=10, overwrite=True, directory='hyperparam_tuning')

In [35]:
# Run the tuner search
tuner.search(x_train, y_train, epochs=20, validation_split=0.2)
best_hyperparams = tuner.get_best_hyperparameters(num_trials=1)[0]
best_model = tuner.hypermodel.build(best_hyperparams)

Trial 10 Complete [00h 00m 19s]
val_accuracy: 0.9496874809265137

Best val_accuracy So Far: 0.9503124952316284
Total elapsed time: 00h 03m 18s


In [37]:
# Train the best model from the search
best_model.fit(x_train, y_train, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.3548 - loss: 2.2522 - val_accuracy: 0.7169 - val_loss: 0.9502
Epoch 2/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7602 - loss: 0.7837 - val_accuracy: 0.8278 - val_loss: 0.6227
Epoch 3/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8321 - loss: 0.5477 - val_accuracy: 0.8537 - val_loss: 0.4853
Epoch 4/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8700 - loss: 0.4308 - val_accuracy: 0.8803 - val_loss: 0.4078
Epoch 5/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8951 - loss: 0.3484 - val_accuracy: 0.8891 - val_loss: 0.3647
Epoch 6/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9123 - loss: 0.2818 - val_accuracy: 0.9022 - val_loss: 0.3278
Epoch 7/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9265 - loss: 0.2417 - val_accuracy: 0.9147 - val_loss: 0.2968
Epoch 8/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9325 - loss: 0.2163 - val_accuracy: 0.

## Evaluation

In [38]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

In [39]:
# Predictions on test data
y_pred_tuned = best_model.predict(x_test)
y_pred_tuned_classes = np.argmax(y_pred_tuned, axis=1)

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step


In [40]:
y_pred_tuned 

array([[7.9389135e-09, 6.3502071e-08, 1.2895533e-10, ..., 1.9794883e-02,
        7.6436467e-05, 8.7358011e-03],
       [1.7648791e-04, 8.5299365e-07, 1.2580261e-03, ..., 4.2931156e-09,
        6.4569053e-07, 2.3260763e-14],
       [1.0000000e+00, 2.7787283e-27, 3.7491512e-15, ..., 1.7321620e-14,
        7.5612347e-20, 9.1978514e-18],
       ...,
       [2.8953227e-08, 2.5165799e-19, 5.6371969e-06, ..., 1.2018059e-13,
        1.7875034e-15, 9.3639552e-15],
       [1.6054182e-03, 2.4203699e-08, 1.1334901e-11, ..., 4.9029952e-10,
        9.8174745e-01, 4.4835208e-05],
       [1.3971701e-13, 1.7238830e-21, 2.3568576e-17, ..., 7.4159824e-11,
        9.9999988e-01, 7.2249132e-15]], dtype=float32)

In [41]:
y_pred_tuned_classes 

array([19, 11,  0, ..., 16, 24, 24], dtype=int64)

In [42]:
# Calculate performance metrics
accuracy = accuracy_score(y_test, y_pred_tuned_classes)
precision = precision_score(y_test, y_pred_tuned_classes, average='weighted')
recall = recall_score(y_test, y_pred_tuned_classes, average='weighted')
f1 = f1_score(y_test, y_pred_tuned_classes, average='weighted')

In [43]:
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print("Classification Report:\n", classification_report(y_test, y_pred_tuned_classes))

Accuracy: 0.94025
Precision: 0.942029952742941
Recall: 0.94025
F1 Score: 0.9404080584468597
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.97      0.98       149
           1       0.96      0.86      0.90       153
           2       0.90      0.94      0.92       137
           3       0.97      0.92      0.95       156
           4       0.97      0.89      0.93       141
           5       0.86      0.96      0.91       140
           6       0.97      0.91      0.94       160
           7       0.89      0.88      0.89       144
           8       0.99      0.89      0.94       146
           9       0.92      0.97      0.94       149
          10       0.84      0.92      0.88       130
          11       0.97      0.95      0.96       155
          12       0.99      0.98      0.98       168
          13       0.99      0.91      0.94       151
          14       0.91      0.94      0.93       145
          15       